# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str
#           api_key: str
#           api_version: str optional (only for azure)
#     api_type: str
#     tokenizer: str optional (to optimize token limits)
#     parallel: int

Meta-Llama-3.1-405B:
    model_name: meta-llama/Meta-Llama-3.1-405B
    endpoints: null
    api_type: huggingface
    parallel: 8

gpt-3.5-turbo-0125:
    model_name: gpt-3.5-turbo-0125
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4o-mini-2024-07-18:
    model_name: gpt-4o-mini-2024-07-18
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-turbo-2024-04-09:
    model_name: gpt-4-turbo-2024-04-09
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-0314:
    model_name: gpt-4-0314
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-1106-preview:
    model_name: gpt-4-1106-preview
    endpoints: null
    api_type: openai
    parallel: 8

claude-3-5-sonnet-20240620:
    model_name: claude-3-5-sonnet-20240620
    endpoints: null
    api_type: anthropic
    parallel: 8

facebook/opt-125m:
    model_name: facebook/opt-125m
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

Qwen/Qwen3-30B-A3B:
    model_name: qwen3:30b-a3b
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 1

meta-llama/Meta-Llama-3-8B:
    model_name: meta-llama/Meta-Llama-3-8B
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

Meta-Llama-3.1-405B:
    model_name: meta-llama/Meta-Llama-3.1-405B
    endpoints: null
    api_type: huggingface
    parallel: 8

Qwen/Qwen2.5-7B-Instruct:
    model_name: Qwen/Qwen2.5-7B-Instruct
    endpoints: null
    api_type: huggingface
    parallel: 8

Qwen/Qwen2.5-3B-Instruct:
    model_name: Qwen/Qwen2.5-3B-Instruct
    endpoints: null
    api_type: huggingface_local
    parallel: 1

hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4:
    model_name: hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4
    endpoints: null
    api_type: huggingface_local
    parallel: 1

QuantFactory/Meta-Llama-3.1-8B-GGUF:
    model_name: QuantFactory/Meta-Llama-3.1-8B-GGUF
    endpoints: null
    api_type: huggingface_local
    parallel: 1

google/gemma-2-9b-it:
    model_name: google/gemma-2-9b-it
    endpoints: null
    api_type: huggingface_local
    parallel: 1

Magpie-Align/Llama-3-8B-WizardLM-196K:
    model_name: Magpie-Align/Llama-3-8B-WizardLM-196K
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

Dynosaur/llama3-8b-sft-full-mn:
    model_name: Dynosaur/llama3-8b-sft-full-mn
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

openchat/openchat-3.6-8b-20240522:
    model_name: openchat/openchat-3.6-8b-20240522
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

jondurbin/bagel-8b-v1.0:
    model_name: jondurbin/bagel-8b-v1.0
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

cognitivecomputations/dolphin-2.9-llama3-8b:
    model_name: cognitivecomputations/dolphin-2.9-llama3-8b
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8
    
meta-llama/Llama-3.1-8B-Instruct:
    model_name: meta-llama/Llama-3.1-8B-Instruct
    endpoints:
        - api_base: https://api.together.xyz/v1
    api_type: together
    parallel: 8

mistralai/Mixtral-8x7B-Instruct-v0.1:
    model_name: mistralai/Mixtral-8x7B-Instruct-v0.1
    endpoints:
        - api_base: https://api.together.xyz/v1
    api_type: together
    parallel: 8
    
qwen/Qwen2-7B-Instruct:
    model_name: qwen/Qwen2-7B-Instruct
    endpoints:
        - api_base: https://api.together.xyz/v1
    api_type: together
    parallel: 8

qwen/QwQ-32B:
    model_name: qwen/QwQ-32B
    endpoints:
        - api_base: https://api.together.xyz/v1
    api_type: together
    parallel: 8

Magpie-Align/Llama-3-8B-Ultrachat-200K:
    model_name: Magpie-Align/Llama-3-8B-Ultrachat-200K
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

Magpie-Align/Llama-3-8B-ShareGPT-112K:
    model_name: Magpie-Align/Llama-3-8B-ShareGPT-112K
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

Magpie-Align/Llama-3-8B-Tulu-330K:
    model_name: Magpie-Align/Llama-3-8B-Tulu-330K
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

Magpie-Align/Llama-3-8B-OpenHermes-243K:
    model_name: Magpie-Align/Llama-3-8B-OpenHermes-243K
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

Magpie-Align/Llama-3-8B-WildChat:
    model_name: Magpie-Align/Llama-3-8B-WildChat
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

Magpie-Align/Llama-3-8B-Magpie-Align-v0.2:
    model_name: Magpie-Align/Llama-3-8B-Magpie-Align-v0.2
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

Magpie-Align/Llama-3-8B-Magpie-Align-SFT-v0.2:
    model_name: Magpie-Align/Llama-3-8B-Magpie-Align-SFT-v0.2
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

princeton-nlp/Llama-3-Base-8B-SFT:
    model_name: princeton-nlp/Llama-3-Base-8B-SFT
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

princeton-nlp/Llama-3-Base-8B-SFT-ORPO:
    model_name: princeton-nlp/Llama-3-Base-8B-SFT-ORPO
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

princeton-nlp/Llama-3-Base-8B-SFT-DPO:
    model_name: princeton-nlp/Llama-3-Base-8B-SFT-DPO
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

ntnhan/Llama3-8B-MetaMath:
    model_name: ntnhan/Llama3-8B-MetaMath
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

hkust-nlp/dart-math-llama3-8b-prop2diff:
    model_name: hkust-nlp/dart-math-llama3-8b-prop2diff
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

ajibawa-2023/Code-Llama-3-8B:
    model_name: ajibawa-2023/Code-Llama-3-8B
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

HenryJJ/llama3-8B-lima:
    model_name: HenryJJ/llama3-8B-lima
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

Replete-AI/Replete-Coder-Llama3-8B:
    model_name: Replete-AI/Replete-Coder-Llama3-8B
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

allenai/llama-3-tulu-2-dpo-8b:
    model_name: allenai/llama-3-tulu-2-dpo-8b
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

anonppp/Llama-3-8B-NuminaCoT:
    model_name: anonppp/Llama-3-8B-NuminaCoT
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

anonppp/Llama-3-8B-tulu-human:
    model_name: anonppp/Llama-3-8B-tulu-human
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8

NousResearch/Hermes-2-Pro-Llama-3-8B:
    model_name: NousResearch/Hermes-2-Pro-Llama-3-8B
    endpoints:
        - api_base: http://localhost:11434/v1
          api_key: 12345
    api_type: openai
    parallel: 8